# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  buildBackend:
    name: Build Backend
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: oven-sh/setup-bun@v1

    - run: cd anify-backend && bun run install
    - run: cd anify-backend && bun run lint
    - run: cd anify-backend && bun run build
  buildFrontend:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: oven-sh/setup-bun@v1

    - run: cd anify-frontend && bun run install
    - run: cd anify-frontend && bun run lint
    - run: cd anify-frontend && bun run build
